// https://developer.mapquest.com/documentation/tools/latitude-longitude-finder/

module.exports = [
  {
    city: 'New York',
    state: 'New York',
    lon: '-73.93',
    lat: '40.66',
  },
  {
    city: 'Los Angeles',
    state: 'California',
    lon: '-118.41',
    lat: '34.01',
  },
  {
    city: 'Chicago',
    state: 'Illinois',
    lon: '-87.68',
    lat: '41.83',
  },
  {
    city: 'Houston',
    state: 'Texas',
    lon: '-95.39',
    lat: '29.78',
  },
  {
    city: 'Phoenix',
    state: 'Arizona',
    lon: '-112.09',
    lat: '33.57',
  },
  {
    city: 'Philadelphia',
    state: 'Pennsylvania',
    lon: '-75.13',
    lat: '40.00',
  },
  {
    city: 'San Antonio',
    state: 'Texas',
    lon: '-98.52',
    lat: '29.47',
  },
  {
    city: 'San Diego',
    state: 'California',
    lon: '-117.13',
    lat: '32.81',
  },
  {
    city: 'Dallas',
    state: 'Texas',
    lon: '-96.76',
    lat: '32.79',
  },
  {
    city: 'San Jose',
    state: 'California',
    lon: '-121.81',
    lat: '37.29',
  },
  {
    city: 'Austin',
    state: 'Texas',
    lon: '-97.75',
    lat: '30.30',
  },
  {
    city: 'Jacksonville',
    state: 'Florida',
    lon: '-81.66',
    lat: '30.33',
  },
  {
    city: 'Fort Worth',
    state: 'Texas',
    lon: '-97.34',
    lat: '32.78',
  },
  {
    city: 'Columbus',
    state: 'Ohio',
    lon: '-82.98',
    lat: '39.98',
  },
  {
    city: 'Indianapolis',
    state: 'Indiana',
    lon: '-86.14',
    lat: '39.77',
  },
  {
    city: 'Charlotte',
    state: 'North Carolina',
    lon: '-80.83',
    lat: '35.20',
  },
  {
    city: 'San Francisco',
    state: 'California',
    lon: '-123.03',
    lat: '37.72',
  },
  {
    city: 'Seattle',
    state: 'Washington',
    lon: '-122.35',
    lat: '47.62',
  },
  {
    city: 'Denver',
    state: 'Colorado',
    lon: '-104.88',
    lat: '39.76',
  },
  {
    city: 'Washington',
    state: 'District of Columbia',
    lon: '-77.01',
    lat: '38.90',
  },
  {
    city: 'Nashville',
    state: 'Tennessee',
    lon: '-86.78',
    lat: '36.17',
  },
  {
    city: 'Oklahoma City',
    state: 'Oklahoma',
    lon: '-97.51',
    lat: '35.46',
  },
  {
    city: 'El Paso',
    state: 'Texas',
    lon: '-106.42',
    lat: '31.84',
  },
  {
    city: 'Boston',
    state: 'Massachusetts',
    lon: '-71.02',
    lat: '42.33',
  },
  {
    city: 'Portland',
    state: 'Oregon',
    lon: '-122.65',
    lat: '45.53',
  },
  {
    city: 'Las Vegas',
    state: 'Nevada',
    lon: '-115.26',
    lat: '36.22',
  },
  {
    city: 'Detroit',
    state: 'Michigan',
    lon: '-83.10',
    lat: '42.38',
  },
  {
    city: 'Memphis',
    state: 'Tennessee',
    lon: '-89.97',
    lat: '35.10',
  },
  {
    city: 'Louisville',
    state: 'Kentucky',
    lon: '-85.64',
    lat: '38.16',
  },
  {
    city: 'Baltimore',
    state: 'Maryland',
    lon: '-76.61',
    lat: '39.30',
  },
  {
    city: 'Milwaukee',
    state: 'Wisconsin',
    lon: '-87.96',
    lat: '43.06',
  },
  {
    city: 'Albuquerque',
    state: 'New Mexico',
    lon: '-106.64',
    lat: '35.10',
  },
  {
    city: 'Tucson',
    state: 'Arizona',
    lon: '-110.87',
    lat: '32.15',
  },
  {
    city: 'Fresno',
    state: 'California',
    lon: '-119.79',
    lat: '36.78',
  },
  {
    city: 'Sacramento',
    state: 'California',
    lon: '-121.46',
    lat: '38.56',
  },
  {
    city: 'Kansas City',
    state: 'Missouri',
    lon: '-94.55',
    lat: '39.12',
  },
  // {
  //   city: 'Mesa',
  //   state: 'Arizona',
  //   lon: '-111.71',
  //   lat: '33.40',
  // },
  {
    city: 'Atlanta',
    state: 'Georgia',
    lon: '-84.42',
    lat: '33.76',
  },
  {
    city: 'Omaha',
    state: 'Nebraska',
    lon: '-96.04',
    lat: '41.26',
  },
  {
    city: 'Colorado Springs',
    state: 'Colorado',
    lon: '-104.76',
    lat: '38.86',
  },
  {
    city: 'Raleigh',
    state: 'North Carolina',
    lon: '-78.64',
    lat: '35.83',
  },
  {
    city: 'Long Beach',
    state: 'California',
    lon: '-118.15',
    lat: '33.80',
  },
  {
    city: 'Virginia Beach',
    state: 'Virginia',
    lon: '-76.02',
    lat: '36.78',
  },
  {
    city: 'Miami',
    state: 'Florida',
    lon: '-80.20',
    lat: '25.77',
  },
  {
    city: 'Oakland',
    state: 'California',
    lon: '-122.22',
    lat: '37.76',
  },
  {
    city: 'Minneapolis',
    state: 'Minnesota',
    lon: '-93.26',
    lat: '44.96',
  },
  {
    city: 'Tulsa',
    state: 'Oklahoma',
    lon: '-95.90',
    lat: '36.12',
  },
  {
    city: 'Bakersfield',
    state: 'California',
    lon: '-119.01',
    lat: '35.32',
  },
  {
    city: 'Wichita',
    state: 'Kansas',
    lon: '-97.34',
    lat: '37.69',
  },
  // {
  //   city: 'Arlington',
  //   state: 'Texas',
  //   lon: '-97.12',
  //   lat: '32.70',
  // },
  // {
  //   city: 'Aurora',
  //   state: 'Colorado',
  //   lon: '-104.68',
  //   lat: '39.68',
  // },
  {
    city: 'Tampa',
    state: 'Florida',
    lon: '-82.47',
    lat: '27.97',
  },
  {
    city: 'New Orleans',
    state: 'Louisiana',
    lon: '-89.93',
    lat: '30.05',
  },
  {
    city: 'Cleveland',
    state: 'Ohio',
    lon: '-81.67',
    lat: '41.47',
  },
  {
    city: 'Honolulu',
    state: 'Hawaii',
    lon: '-157.84',
    lat: '21.32',
  },
  // {
  //   city: 'Anaheim',
  //   state: 'California',
  //   lon: '-117.76',
  //   lat: '33.85',
  // },
  {
    city: 'Lexington',
    state: 'Kentucky',
    lon: '-84.45',
    lat: '38.04',
  },
  // {
  //   city: 'Stockton',
  //   state: 'California',
  //   lon: '-121.31',
  //   lat: '37.97',
  // },
  {
    city: 'Corpus Christi',
    state: 'Texas',
    lon: '-97.17',
    lat: '27.75',
  },
  // {
  //   city: 'Henderson',
  //   state: 'Nevada',
  //   lon: '-115.03',
  //   lat: '36.00',
  // },
  // {
  //   city: 'Riverside',
  //   state: 'California',
  //   lon: '-117.39',
  //   lat: '33.93',
  // },
  // {
  //   city: 'Newark',
  //   state: 'New Jersey',
  //   lon: '-74.17',
  //   lat: '40.72',
  // },
  // {
  //   city: 'Saint Paul',
  //   state: 'Minnesota',
  //   lon: '-93.10',
  //   lat: '44.94',
  // },
  // {
  //   city: 'Santa Ana',
  //   state: 'California',
  //   lon: '-117.88',
  //   lat: '33.73',
  // },
  {
    city: 'Cincinnati',
    state: 'Ohio',
    lon: '-84.50',
    lat: '39.14',
  },
  // {
  //   city: 'Irvine',
  //   state: 'California',
  //   lon: '-117.77',
  //   lat: '33.67',
  // },
  {
    city: 'Orlando',
    state: 'Florida',
    lon: '-81.27',
    lat: '28.41',
  },
  {
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    lon: '-79.97',
    lat: '40.43',
  },
  {
    city: 'St. Louis',
    state: 'Missouri',
    lon: '-90.24',
    lat: '38.63',
  },
  {
    city: 'Greensboro',
    state: 'North Carolina',
    lon: '-79.82',
    lat: '36.09',
  },
  {
    city: 'Jersey City',
    state: 'New Jersey',
    lon: '-74.06',
    lat: '40.71',
  },
  {
    city: 'Anchorage',
    state: 'Alaska',
    lon: '-149.28',
    lat: '61.17',
  },
  {
    city: 'Lincoln',
    state: 'Nebraska',
    lon: '-96.68',
    lat: '40.81',
  },
  {
    city: 'Plano',
    state: 'Texas',
    lon: '-96.74',
    lat: '33.05',
  },
  {
    city: 'Durham',
    state: 'North Carolina',
    lon: '-78.90',
    lat: '35.98',
  },
  {
    city: 'Buffalo',
    state: 'New York',
    lon: '-78.85',
    lat: '42.89',
  },
  {
    city: 'Chandler',
    state: 'Arizona',
    lon: '-111.85',
    lat: '33.28',
  },
  // {
  //   city: 'Chula Vista',
  //   state: 'California',
  //   lon: '-117.01',
  //   lat: '32.62',
  // },
  {
    city: 'Toledo',
    state: 'Ohio',
    lon: '-83.58',
    lat: '41.66',
  },
  {
    city: 'Madison',
    state: 'Wisconsin',
    lon: '-89.42',
    lat: '43.08',
  },
  {
    city: 'Gilbert',
    state: 'Arizona',
    lon: '-111.74',
    lat: '33.31',
  },
  {
    city: 'Reno',
    state: 'Nevada',
    lon: '-119.84',
    lat: '39.54',
  },
  {
    city: 'Fort Wayne',
    state: 'Indiana',
    lon: '-85.14',
    lat: '41.08',
  },
  {
    city: 'North Las Vegas',
    state: 'Nevada',
    lon: '-115.09',
    lat: '36.28',
  },
  // {
  //   city: 'St. Petersburg',
  //   state: 'Florida',
  //   lon: '-82.64',
  //   lat: '27.76',
  // },
  {
    city: 'Lubbock',
    state: 'Texas',
    lon: '-101.88',
    lat: '33.56',
  },
  // {
  //   city: 'Irving',
  //   state: 'Texas',
  //   lon: '-96.97',
  //   lat: '32.85',
  // },
  {
    city: 'Laredo',
    state: 'Texas',
    lon: '-99.48',
    lat: '27.56',
  },
  {
    city: 'Winston–Salem',
    state: 'North Carolina',
    lon: '-80.26',
    lat: '36.10',
  },
  {
    city: 'Chesapeake',
    state: 'Virginia',
    lon: '-76.30',
    lat: '36.67',
  },
  // {
  //   city: 'Glendale',
  //   state: 'Arizona',
  //   lon: '-112.18',
  //   lat: '33.53',
  // },
  {
    city: 'Garland',
    state: 'Texas',
    lon: '-96.63',
    lat: '32.90',
  },
  // {
  //   city: 'Scottsdale',
  //   state: 'Arizona',
  //   lon: '-111.86',
  //   lat: '33.68',
  // },
  {
    city: 'Norfolk',
    state: 'Virginia',
    lon: '-76.24',
    lat: '36.92',
  },
  {
    city: 'Boise',
    state: 'Idaho',
    lon: '-116.23',
    lat: '43.60',
  },
  {
    city: 'Fremont',
    state: 'California',
    lon: '-121.94',
    lat: '37.49',
  },
  {
    city: 'Spokane',
    state: 'Washington',
    lon: '-117.43',
    lat: '47.66',
  },
  {
    city: 'Santa Clarita',
    state: 'California',
    lon: '-118.50',
    lat: '34.40',
  },
  {
    city: 'Baton Rouge',
    state: 'Louisiana',
    lon: '-91.13',
    lat: '30.44',
  },
  {
    city: 'Richmond',
    state: 'Virginia',
    lon: '-77.47',
    lat: '37.53',
  },
  {
    city: 'Fargo',
    state: 'North Dakota',
    lon: '-96.7898',
    lat: '46.87719',
  },
  {
    city: 'Des Moines',
    state: 'Iowa',
    lon: '-93.60911',
    lat: '41.60054',
  },
  {
    city: 'Birmingham',
    state: 'Alabama',
    lon: '-86.80249',
    lat: '33.52066',
  },
  {
    city: 'Salt Lake City',
    state: 'Utah',
    lon: '-111.89105',
    lat: '40.76078',
  },
  {
    city: 'Little Rock',
    state: 'Arkansas',
    lon: '-92.28959',
    lat: '34.74648',
  },
  {
    city: 'Sioux Falls',
    state: 'South Dakota',
    lon: '-96.70033',
    lat: '43.54997',
  },
  {
    city: 'Knoxville',
    state: 'Tennessee',
    lon: '-83.92074',
    lat: '35.96064',
  },
  {
    city: 'Chattanooga',
    state: 'Tennessee',
    lon: '-85.30968',
    lat: '35.04563',
  },
  {
    city: 'Shreveport',
    state: 'Louisiana',
    lon: '-93.75018',
    lat: '32.52515',
  },
  {
    city: 'Waco',
    state: 'Texas',
    lon: '-97.14667',
    lat: '31.54933',
  },
];
